const ACTION_TYPES = {
  // NEWS

  // Post
  SET_CURRENT_POST:  'SET_CURRENT_POST',
  EDIT_CURRENT_POST: 'EDIT_CURRENT_POST',


  // ACCOUNT
  SET_USER_DATA:  'SET_USER_DATA',
  EDIT_USER_DATA: 'EDIT_USER_DATA',
};

export default ACTION_TYPES;
