const ACTION_TYPES = {
  // ACCOUNT
  SET_USER_DATA: 'SET_USER_DATA',
  EDIT_USER_DATA: 'EDIT_USER_DATA',


  // NEWS

  // Post
  SET_CURRENT_POST:  'SET_CURRENT_POST',

  // Blog
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_POSTS:      'SET_POSTS',
};

export default ACTION_TYPES;
