const ACTION_TYPES = {
  // NEWS

  // Post
  GET_CURRENT_POST:  'GET_CURRENT_POST',
  EDIT_CURRENT_POST: 'EDIT_CURRENT_POST',

  // Blog
  GET_POSTS:      'GET_POSTS',
  GET_CATEGORIES: 'GET_CATEGORIES',


  // ACCOUNT
  SET_USER_DATA:  'SET_USER_DATA',
  EDIT_USER_DATA: 'EDIT_USER_DATA'
};

export default ACTION_TYPES;
